# Generated by Django 3.1.2 on 2020-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('U', 'Undefined'), ('F', 'Female'), ('M', 'Male')], default='U', max_length=2),
        ),
    ]
